name: Build ISO with FM-DX Webserver

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types:
      - fm-dx-webserver-updated

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Clone FM-DX Webserver
      run: |
        git clone https://github.com/NoobishSVK/fm-dx-webserver.git fm-dx-webserver
        cd fm-dx-webserver
        git pull

    - name: Install Required Deps
      run: |
        sudo apt update && sudo apt install -y \
          qemu-utils \
          curl \
          xz-utils \
          dosfstools \
          kpartx

    - name: Download and Extract RPi OS Lite
      run: |
        mkdir -p images
        curl -L -o images/rpi-os-lite.img.xz https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2024-01-01/2024-01-01-raspios-bullseye-armhf-lite.img.xz
        # Check if the file is correctly downloaded
        file images/rpi-os-lite.img.xz
        # Ensure the file is the correct XZ compressed image
        if file images/rpi-os-lite.img.xz | grep -q "XZ compressed data"; then
          unxz images/rpi-os-lite.img.xz
        else
          echo "Downloaded file is not the expected image file. Exiting."
          exit 1
        fi

    - name: Create a loop device and mount the image
      run: |
        sudo losetup --find --show images/rpi-os-lite.img
        LOOP_DEVICE=$(sudo losetup --find --show images/rpi-os-lite.img)
        sudo kpartx -a $LOOP_DEVICE
        sudo mount /dev/mapper/loop0p2 mnt

    - name: Customize the Image
      run: |
        sudo mkdir -p mnt/home/pi
        sudo cp -r fm-dx-webserver mnt/home/pi/
        sudo cp setup.sh mnt/home/pi/
        sudo chroot mnt /bin/bash -c "/home/pi/setup.sh"
        sudo umount mnt

    - name: Compress the Image
      run: |
        mv images/rpi-os-lite.img images/rpi-os-lite.img.original
        xz -z -9 images/rpi-os-lite.img.original
        mv images/rpi-os-lite.img.xz custom-fm-dx-webserver.img.xz

    - name: Upload ISO Artifact
      uses: actions/upload-artifact@v3
      with:
        name: custom-fm-dx-webserver
        path: custom-fm-dx-webserver.img.xz
